title: JYW-CTest
description: Course Test
template:
  repo: jyw-ctest-template
  name: jyw-ctest
  description: 'Welcome, my friend'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
